#!/bin/bash

# gex "go get"s and executes Go programs.
#
# usage: gex [options] pkg [args...]

set -e

export GOBIN="$PWD/.bin"

main() {
    done=
    opts=()
    while [ ! "$done" ] && [ "$#" -gt 0 ]; do
        case "$1" in
            -*)
                opts+=("$1")
                shift
                ;;
            *)
                pkg=$1
                done=1
                shift
                ;;
        esac
    done

    if [ -z "$pkg" ]; then
        usage
    fi

    go get "${opts[@]}" "$pkg"

    if ! [ "$(go list -f '{{.Name}}' "$pkg")" = 'main' ]; then
        die "fatal: package $pkg is not an executable"
    fi

    exec "$GOBIN/$(basename "$pkg")" "$@"
}

usage() {
    cat >&2 <<USAGE
usage: $0 [options] pkg [args...]
USAGE
    exit 2
}

die() {
    echo "$@" >&2
    exit 1
}

main "$@"
